# Generated by Django 3.2 on 2021-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_deanapp_dirapp_hodapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=6)),
                ('pos', models.CharField(max_length=10)),
                ('curr_pos', models.CharField(default='default', max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='mec_dep',
            new_name='cse_dept',
        ),
        migrations.RenameModel(
            old_name='ee_dep',
            new_name='ee_dept',
        ),
        migrations.RenameModel(
            old_name='cse_dep',
            new_name='mec_dept',
        ),
        migrations.DeleteModel(
            name='login_table',
        ),
    ]
